In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
!pip install -U scikit-learn
!pip install scikit-learn==1.8.0
import sklearn
print(sklearn.__version__)

In [ ]:
df=pd.read_csv("ecommerce_sales_data (2).csv")

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df.head()

  Order Date Product Name     Category Region  Quantity  Sales  Profit
0 2024-12-31      Printer       Office  North         4   3640  348.93
1 2022-11-27        Mouse  Accessories   East         7   1197  106.53
2 2022-05-11       Tablet  Electronics  South         5   5865  502.73
3 2024-03-16        Mouse  Accessories  South         2    786  202.87
4 2022-09-10        Mouse  Accessories   West         1    509  103.28

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Day"] = df["Order Date"].dt.day

In [ ]:
df.tail()

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month,Day
3495,2023-02-15,Monitor,Accessories,North,4,4064,771.16,2023,2,15
3496,2022-09-18,Monitor,Accessories,East,1,1117,119.89,2022,9,18
3497,2022-04-12,Laptop,Electronics,South,4,260,66.02,2022,4,12
3498,2022-01-18,Printer,Office,South,3,222,50.28,2022,1,18
3499,2024-11-01,Smartwatch,Electronics,East,9,10530,1777.32,2024,11,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   datetime64[ns]
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
 7   Year          3500 non-null   int32
 8   Month         3500 non-null   int32
 9   Day           3500 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), int64(2), object(3)
memory usage: 232.6+ KB

In [ ]:
df.describe()

,Order Date,Quantity,Sales,Profit,Year,Month,Day
count,3500,3500.000000,3500.000000,3500.000000,3500.000000,3500.000000,3500.000000
mean,2023-07-13 00:53:53.828571648,4.931714,3047.966000,527.047203,2023.030857,6.512286,15.639714
min,2022-01-01 00:00:00,1.000000,51.000000,6.970000,2022.000000,1.000000,1.000000
25%,2022-10-16 18:00:00,3.000000,1049.500000,158.695000,2022.000000,4.000000,8.000000
50%,2023-07-21 12:00:00,5.000000,2350.500000,361.070000,2023.000000,6.000000,16.000000
75%,2024-04-16 06:00:00,7.000000,4537.000000,729.125000,2024.000000,10.000000,23.000000
max,2024-12-31 00:00:00,9.000000,10782.000000,2946.930000,2024.000000,12.000000,31.000000
std,NaN,2.575895,2440.213237,504.139732,0.809466,3.447415,8.716989

In [ ]:
df.isna().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
Year            0
Month           0
Day             0
dtype: int64

In [ ]:
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Total Quantity:", df["Quantity"].sum())

Total Sales: 10667881
Total Profit: 1844665.21
Total Quantity: 17261

In [ ]:
# Top products
top_products = df.groupby("Product Name")[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print(top_products)

# Region analysis
region_sales = df.groupby("Region")[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print(region_sales)

# Category analysis
category_sales = df.groupby("Category")[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print(category_sales)

# Monthly trend
df['Order Date'] = pd.to_datetime(df['Order Date'])
monthly_sales = df.groupby(df["Order Date"].dt.to_period("M"))["Sales"].sum()
print(monthly_sales)

                Sales     Profit
Product Name
Camera        1177381  207630.99
Monitor       1160048  202028.17
Printer       1094216  185394.88
Mouse         1074398  185763.69
Smartphone    1069681  183296.97
Smartwatch    1049211  178995.81
Keyboard      1024507  175814.68
Tablet        1023928  167505.01
Laptop        1005873  185756.81
Headphones     988638  172478.20
          Sales     Profit
Region
West    2844450  495358.73
East    2675110  464888.46
South   2659548  458103.27
North   2488773  426314.75
               Sales     Profit
Category
Electronics  5326074  923185.59
Accessories  4247591  736084.74
Office       1094216  185394.88
Order Date
2022-01    341544
2022-02    208775
2022-03    294660
2022-04    230624
2022-05    314295
2022-06    273851
2022-07    214627
2022-08    296242
2022-09    240211
2022-10    324989
2022-11    257111
2022-12    259041
2023-01    343256
2023-02    313931
2023-03    303391
2023-04    280808
2023-05    346481
2023-06    251686
2023-07    320798
2023-08    388428
2023-09    303409
2023-10    253145
2023-11    306195
2023-12    375064
2024-01    282814
2024-02    179708
2024-03    341563
2024-04    310444
2024-05    373911
2024-06    314268
2024-07    309515
2024-08    240269
2024-09    341926
2024-10    314135
2024-11    291769
2024-12    324997
Freq: M, Name: Sales, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Day"] = df["Order Date"].dt.day

In [ ]:
le_product = LabelEncoder()
le_category = LabelEncoder()
le_region = LabelEncoder()

df["Product Name"] = le_product.fit_transform(df["Product Name"])
df["Category"] = le_category.fit_transform(df["Category"])
df["Region"] = le_region.fit_transform(df["Region"])

In [ ]:
X = df[["Product Name", "Category", "Region", "Quantity", "Year", "Month", "Day"]]
y = df["Sales"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error ,r2_score ,mean_absolute_error
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([2205.01      , 1965.53      ,  677.88      , 4850.07      ,
       3344.24      ,  625.75      , 4971.93      , 6185.76      ,
        798.6       , 2474.8       , 6453.18      , 2335.67      ,
       4002.91      , 5350.78      , 2303.88      , 7125.03      ,
       3925.98      , 2923.48      ,  511.51      , 3263.05      ,
       2770.46      , 3508.78      , 2111.7       , 7391.745     ,
       2245.62      , 1725.33      , 3468.25      , 3540.79      ,
       2532.36      , 4171.56      , 4703.55      , 2260.32      ,
       3121.87      , 3959.86      , 4216.11      , 3888.43      ,
       3790.53      , 2336.13      ,  574.82      , 4167.28      ,
       4011.14      ,  617.33      , 2731.11      , 3481.2       ,
       7262.19      , 3520.38      , 4141.48      , 5376.53      ,
        983.48      , 5377.95      ,  528.18      , 3626.01      ,
        594.61      , 2508.0925    , 4565.57      , 4967.24      ,
       1186.04      , 2228.07      , 6702.04      ,  558.12      ,
       3321.21      , 3753.49      , 1988.16      , 3811.15      ,
        795.96      ,  632.97      , 1832.61      , 5714.92      ,
       3194.6       , 2435.06      , 5752.59      , 2859.93      ,
       2608.79      , 2019.2       , 2920.41      , 4740.71      ,
       3303.57      , 1694.13      , 1746.81      , 4711.32      ,
       3890.33      , 1109.56      , 5121.77      , 1774.17      ,
       4398.71      , 4532.39      , 3878.72      , 4971.27      ,
       5215.74      , 2714.        , 1985.63      , 1408.5       ,
       3703.37      , 2356.82      , 1365.88      , 3269.49      ,
       6017.4       , 2692.63      , 3966.02      , 2073.83      ,
       2055.6       , 4670.43      ,  645.83      , 1428.72      ,
       1960.08      , 7273.73      , 1083.51      , 7857.59      ,
       4306.47      , 2152.18      , 1340.46      , 2545.11      ,
       4426.22      ,  766.82      , 4951.5       , 4394.33      ,
       2395.86      , 3431.44      , 1204.48      , 4357.37      ,
       5071.68      ,  774.35      , 8269.92      , 4849.87      ,
       3581.36      , 4223.19      , 3081.37      , 2568.19      ,
       3565.05      , 5795.52      , 1299.4       , 4632.43      ,
        605.36      , 2552.75      , 1413.        , 2350.245     ,
       1750.29      , 1744.86      , 3491.49      , 3834.05      ,
       5531.85      , 2944.34      , 2251.24      , 3618.52      ,
       2999.02      ,  818.36      , 4622.78      , 1178.28      ,
        513.3       , 1097.28      , 1951.77      , 6378.066     ,
       3606.38      , 1661.61      ,  419.71      , 1896.3       ,
       1185.4       , 2136.33      , 4365.39      , 2325.65      ,
       3665.47      , 5097.85      , 1290.99      , 2240.73      ,
       1950.58      , 2957.44      , 3513.19      ,  862.76      ,
       2768.96      , 3389.27      , 6069.61      , 6148.53      ,
       2120.1       , 1035.3       ,  548.91      , 2424.51      ,
       4846.8       , 5411.91      , 3242.47      , 3854.32      ,
       4874.08      , 1603.66      , 3049.28      , 2369.        ,
       4267.01      , 3836.4       , 1470.21      , 2280.425     ,
       4600.57      , 4915.26      , 3885.22      , 3037.09      ,
       6740.85      , 3569.43      , 2888.71      , 2292.52      ,
       7322.166     , 3395.43      , 2141.94      , 1592.68      ,
       1508.44      , 2175.285     , 2314.13      , 2642.3       ,
       4028.85      ,  725.11      , 5636.51      , 2750.04      ,
       2183.49      , 3241.5       , 1665.63      , 1818.6       ,
       1603.39      , 4584.87      , 1160.86      , 1736.38      ,
        474.52      , 2514.2       , 4021.72      , 2537.01      ,
       8014.13      , 7456.056     , 4562.67      , 3323.93      ,
       2502.59      , 2510.93      , 3738.29      ,  907.48      ,
       1457.64      , 4013.65      , 2495.03      , 5409.84      ,
       4942.85      , 5343.96      , 1529.58      , 3553.11      ,
       6183.86      , 4876.56      ,  532.22      , 3051.136     ,
       3944.96      ,  902.71      , 2119.74      , 5323.38      ,
       4425.81      , 3944.29      , 3121.27      , 2740.22      ,
       5124.71      , 1951.98      , 3348.89      , 1710.91      ,
       2366.46      ,  635.12      , 1985.52      , 4604.61      ,
       2524.62      , 5749.74      , 3280.52      , 5405.1       ,
       4783.01      , 2825.12      , 2111.94      , 4494.51      ,
       5370.66      , 4447.16      , 3001.01      , 2034.48      ,
       5067.18      , 1308.52      , 4287.57      , 3075.15      ,
       2528.73      , 2169.27      , 2017.56      , 3600.65      ,
       6175.575     , 2279.16      , 2514.89      , 3162.35      ,
       6370.01      , 2267.3       ,  770.63      , 4044.83      ,
       5683.25      , 3276.98      , 1477.32      , 6260.21      ,
        715.1       , 2153.67      ,  886.51      , 3991.75      ,
       2190.15      ,  549.31      , 2645.0975    , 5749.94      ,
        938.24      , 1296.3       ,  756.66      , 1893.94      ,
       2656.27      , 2938.16      , 5720.3       , 1192.32      ,
       1032.68      , 4241.56      ,  927.83      , 5247.19      ,
       1327.92      , 4629.51      , 5357.46      , 4680.34      ,
        695.26      , 2322.92      , 3171.05      , 2476.36      ,
        964.78      , 4190.31      , 4081.85      , 1124.38      ,
       5348.4       , 5335.81      , 6101.01      , 1423.28      ,
       2968.85      , 1290.78      , 1560.99      , 3888.09      ,
       2168.57      , 3106.54      , 4449.85      , 1770.27      ,
        338.08      , 1349.64      , 1614.62      , 2792.3       ,
       2167.47      , 4199.2       ,  399.68      , 5252.12      ,
        627.94      ,  607.21      , 7034.88      , 3738.14      ,
       3624.11      , 4159.8       , 4377.27      , 4967.77      ,
       3743.75      , 1561.72      , 2627.24      , 3735.47      ,
       4101.93      , 3307.72      , 2177.67      , 2176.32      ,
       3249.27166667, 5042.        , 3195.09      , 2849.18      ,
        918.26      , 3446.23      , 2444.31      , 2914.56      ,
        570.41      , 4098.68      , 1460.54      , 3053.06      ,
        330.13      , 4481.59      , 4288.34      , 7020.3       ,
        408.86      , 2714.01      , 2758.99      ,  668.67      ,
        590.73      ,  551.27      , 3523.97      , 2415.34      ,
       4585.46      , 6031.38      , 5755.41      , 2710.55      ,
       2589.71      ,  595.95      , 4491.33      , 3049.04      ,
       3826.4       , 1660.9025    , 2507.66      , 2020.38      ,
       1082.88      , 6976.95      , 4558.38      ,  488.3       ,
       2813.54      , 5344.05      , 5276.64      , 3888.43      ,
       4606.47      , 2804.085     , 5657.22      , 4414.41      ,
       2868.72      ,  711.68      ,  701.39      , 3433.88      ,
       3349.45      , 3102.19      , 1911.87      , 4541.86      ,
       3781.4       , 6685.7175    , 1088.34      , 1770.06      ,
       1964.55      , 1106.7       ,  560.71      , 1629.99      ,
       2501.06      , 1054.14      , 3821.6       , 1209.64      ,
       4500.53      , 6158.84      ,  511.98      , 5437.95      ,
       4867.6       ,  673.74      , 1558.42      , 1556.88      ,
       5552.1       ,  442.28      , 6359.73      , 1201.38      ,
       3314.36      , 3759.64      , 2504.77      , 1660.22      ,
       2265.31      , 3515.        ,  765.64      , 4426.64      ,
        676.84      , 4625.23      , 1134.8       , 2598.06      ,
       2676.3       , 1905.73      , 4696.5       ,  736.63      ,
       4123.08      , 4936.38      , 2557.08      ,  473.41      ,
       4542.49      , 4083.13      , 3881.72      ,  692.02      ,
        873.16      , 3435.58      , 4064.55      ,  516.88      ,
       5144.45      , 1091.22      , 5924.31      , 3942.45      ,
       2573.31      , 5180.61      , 2469.65      ,  633.79      ,
       5652.89      , 4113.48      ,  814.96      , 4169.07      ,
       2177.64      , 3563.8       , 4960.02      , 2243.07      ,
        365.06      , 2311.19      , 5756.39      , 1621.85      ,
        511.21      , 1555.62      , 1701.99      , 5859.68      ,
       4829.31      , 3983.73      , 2185.74      , 5586.82      ,
       5917.54      , 1734.48      , 6255.8       , 1273.24      ,
        329.45      , 5535.09      , 1091.3       , 5701.58      ,
       4530.3       , 3119.54      ,  621.6       ,  650.49      ,
       4432.23      , 7564.61      , 3473.06      ,  608.08      ,
       4003.65      , 1216.66      , 3308.38      , 2921.32      ,
       4728.35      , 4373.61      , 1314.92      , 4421.73      ,
       1561.68      , 3801.61      , 5665.8       ,  495.07      ,
        555.53      , 3820.63      , 5041.69      , 4515.47      ,
       1974.99      , 3010.07      , 1429.47      , 1055.12      ,
       4440.51      , 3920.73      , 1961.52      , 5538.05      ,
       5050.13      , 6621.66      , 2441.43      , 1541.01      ,
        572.14      , 1104.58      ,  618.96      , 5602.97      ,
       6054.47      , 2240.41333333, 1637.07      , 1408.28      ,
       4232.18      ,  308.8       , 4515.31      , 3311.93      ,
       1454.96      , 5842.46      , 3136.41      , 2257.2       ,
       5041.41      , 1636.92      , 2575.47      , 5721.3       ,
       4645.79      , 3858.35      , 4153.29      , 2086.68      ,
       2689.00666667, 2586.93      , 3436.34      , 5183.01      ,
       4080.82      , 6588.47      , 5008.16      , 2595.12      ,
       1690.24      , 1009.48      , 1484.07      , 2605.45      ,
       5258.09      , 5633.01      , 1637.76      , 3091.11333333,
       6831.565     , 4640.67      , 4565.65      , 1780.4       ,
       4763.75      , 1801.77      , 1360.59      ,  532.19      ,
       5805.58      , 1301.2       , 1227.12      , 4776.2       ,
       4989.59      , 2749.6       , 1567.79      , 1938.39      ,
       2433.64      , 5268.78      , 1496.34      , 2433.12      ,
        872.71      , 5380.6       , 4733.94      , 3581.89      ,
       1576.        , 5833.33      , 4856.3       , 6179.47      ,
       2435.83      , 3554.32      , 2251.08      , 4476.21      ,
       1240.8       , 4974.53      , 3633.77      , 2015.85      ,
       3770.45      ,  953.54      , 1001.64      ,  974.3       ,
       2286.11      , 2465.07      , 2421.55      ,  841.46      ,
        467.63      , 1173.58      , 4553.91      , 3958.11      ,
       6536.32      ,  469.54      , 3526.58      , 2339.76      ,
       2750.28      , 1058.06      , 1680.8       , 3167.35      ,
       4631.32      , 5565.97      , 2947.7       , 2805.12      ,
       4065.34      , 1677.12      , 6463.575     , 4138.99      ,
       3743.46      , 3999.71      ,  529.41      , 1759.83      ,
       5852.64      ,  620.41      , 2631.43      , 1390.56      ,
       4521.9       , 4417.47      , 4687.79      , 2090.92285714,
        840.78      ,  744.09      ,  642.05      , 4713.42      ,
       3514.3       , 2380.76      , 2516.2       , 1600.78      ,
        799.01      ,  698.94      , 3554.61      , 3670.3       ,
       1442.1       , 5982.1       , 7795.42      , 3096.065     ,
       3545.13      , 3431.03      , 1069.56      , 6200.78      ,
        765.78      , 1673.7       , 5216.34      ,  896.29      ,
       4588.83      , 2555.03      , 4809.62      , 2085.94      ,
       4882.01      , 5745.12      , 2522.39      , 3323.73      ,
        503.56      , 2610.71      , 7460.76      , 7511.94      ,
       7090.41      , 2145.69      , 4254.58      , 1705.08      ,
       6155.87      , 5177.52      , 2952.05      , 1281.58      ,
       1109.67      , 2202.53      , 2780.88      , 3441.72      ])

In [ ]:
print("mean absulute error", mean_squared_error(y_test, y_pred))
print("r2_score", r2_score(y_test,y_pred))

mean absulute error 3857652.746269827
r2_score 0.385128041926163

In [ ]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(X_train, y_train)

LinearRegression()

In [ ]:
le_pred = le.predict(X_test)
le_pred

array([3052.92617493, 2946.16571185,  592.64970701, 4450.50058417,
       3662.44272375,  601.57206268, 3794.12719252, 4988.19318456,
        626.02197821, 3632.09537825, 5567.72213636, 2566.03075946,
       3705.10105304, 5490.16272954, 3095.53504996, 5481.43138538,
       4273.04482541, 3706.7846705 ,  529.66551051, 3051.12635178,
       3058.15971691, 4490.08680648, 2346.68664454, 5428.17010629,
       1822.2988595 , 1827.85628015, 3583.56567103, 4323.15649303,
       2575.89179975, 3150.92927727, 5068.25714334, 1863.75536574,
       2452.65591415, 4281.2465711 , 3720.06472645, 3062.27984205,
       3575.53025665, 1786.32514922, 1189.17806356, 4919.6509338 ,
       3537.37819975,  772.0011962 , 2598.03125568, 5537.29504015,
       5488.43130802, 3238.17110659, 4277.82028901, 5644.60363803,
       1225.10848895, 5548.08542272,  689.30591165, 3798.02169924,
        552.0367128 , 3128.44800234, 4413.28159566, 4818.93450879,
       1356.94031617, 2467.38633453, 5620.56028538,  461.53147282,
       3057.260394  , 4234.53902993, 2422.36753682, 2974.97438185,
       1195.81517151,  592.92866143, 3737.95954176, 4962.8708082 ,
       2368.40117157, 3161.27438494, 4997.82624263, 2552.64205707,
       3580.97971817, 2632.48844611, 2390.49111955, 3875.9551263 ,
       2980.01070007, 1822.11805857, 1949.11139814, 5494.9876219 ,
       4867.32942029, 1269.40774681, 4197.46679303, 1786.06322445,
       4305.27243079, 4446.84960942, 4235.39295444, 4449.4398965 ,
       4964.4369526 , 2989.52310229, 1980.90288501, 1248.46665406,
       4321.07149239, 3211.95392651, 1099.48061017, 3667.90638738,
       5446.49421021, 2383.16581156, 4982.28890873, 3122.74383007,
       1729.23603456, 4328.39230798,  648.13788841, 1144.75277227,
       1833.66542582, 4823.80553907, 2011.38324205, 5698.85682014,
       4178.87621825, 2456.18609951, 1228.25718976, 1863.18083218,
       4897.29632462,  514.35273572, 5015.38688821, 3670.9519253 ,
       1814.63077898, 4389.99479116, 1098.85392751, 4996.04417867,
       4848.88542683,  628.29364531, 5654.41780002, 5508.82472928,
       3714.35170079, 4203.65045981, 4861.59283808, 3110.91707186,
       4232.12137751, 5034.43009543, 1175.52565351, 4241.13030296,
       1189.11684918, 1755.05476478, 1675.18369554, 3069.99510386,
       1848.20476633, 1806.5774351 , 3708.88984683, 3727.60197731,
       4761.35242094, 3687.92309485, 1804.23892656, 3600.44352009,
       3079.30030638, 1183.83311213, 4319.44805677, 1225.77187608,
        510.33519341, 1189.20492563, 3118.05390371, 5573.0586977 ,
       3190.5547286 , 1903.41292318,  659.91414771, 1922.04057061,
       1324.49602494, 1820.02066549, 5080.9188532 , 3013.0656609 ,
       3669.42803324, 4334.40048707, 1877.81507904, 3061.75024358,
       2502.38579422, 2511.80474241, 3764.25767538,  616.72982846,
       3058.26092661, 3738.13315544, 4835.81416751, 5618.83840327,
       1964.24079603, 1222.01277191,  625.00726899, 2010.00212474,
       4962.01973672, 4852.15656722, 3801.6301554 , 4403.24852754,
       4442.83250365, 1238.5264699 , 2453.12353194, 3701.28134132,
       3715.0375111 , 3599.25603269, 2034.18390325, 1852.75147058,
       4187.44167846, 4241.81712986, 4426.15187835, 4150.43126278,
       5558.69319469, 3783.73699029, 3745.48261599, 1804.60324791,
       5618.85092969, 3707.14216196, 2485.4631536 , 1289.20870503,
       1329.42661941, 1879.70058295, 3107.28430367, 3116.56301632,
       3547.95611181,  649.51231935, 5405.00409119, 3009.80869712,
       1792.53504447, 2537.24106231, 1714.23522014, 1860.52916043,
       1809.19549407, 4984.45546974, 1151.49184027, 2607.16502639,
        677.02584581, 2975.26374874, 4235.59094449, 2524.92453066,
       5469.9452325 , 5470.83959969, 5533.37517803, 4270.10694363,
       2940.68653522, 2351.87810447, 3755.07567874,  528.82844535,
       1326.80873073, 4183.91192964, 3065.41884398, 4310.94916093,
       5520.08678551, 4289.29810531, 1194.33352097, 4922.55627293,
       5542.94728796, 4325.72706643,  704.44544495, 2458.08385234,
       4767.88187276,  706.98194355, 2435.45763546, 5547.20268167,
       4290.52977744, 3635.80894051, 4344.2464509 , 2436.62628354,
       3743.48035307, 1860.49480812, 4261.88968495, 3732.11604377,
       3097.60436731,  757.40167385, 1904.41510598, 4307.84720487,
       3098.43008339, 5447.43306512, 4293.57216932, 5543.14588485,
       4223.84153131, 3699.41105739, 1832.96949605, 4240.46016511,
       4163.94465095, 4194.30378206, 2446.97424425, 2415.68939018,
       3718.38447903, 1230.45001683, 4327.58452139, 3112.17041041,
       3718.34180097, 3221.554719  , 1714.72257709, 4976.42808809,
       5523.85931595, 2393.2272584 , 2314.8361895 , 3790.79648794,
       4954.57305928, 3143.74674403,  522.31094944, 3192.02872987,
       4790.14497112, 3616.45326802, 1978.22300482, 4201.54632685,
       1096.12971907, 2510.37940362,  732.58371086, 3713.71594203,
       1922.95302676,  560.99935552, 3085.45463026, 4882.64173177,
       1142.74376946, 1179.50067723,  521.79551676, 3099.15811927,
       4343.38298698, 3135.18008098, 5571.42670171, 1118.22769979,
       1205.7635587 , 4364.88265377,  684.05306705, 4963.08733457,
       1313.29309636, 4312.0778137 , 5468.31203367, 4205.35381643,
        638.8670382 , 2403.22822041, 4325.75917254, 2424.41193531,
       1202.46313974, 3245.52056714, 3600.68614223, 1146.10779381,
       4303.49727702, 5479.2863732 , 5646.36925239, 1138.96734262,
       3209.42425781, 1208.21166704, 1828.32721429, 2515.71596496,
       2385.11523936, 3736.483124  , 3553.4340856 , 1823.83692818,
        531.49190271, 1278.9219587 , 1313.65966392, 3721.10748463,
       2508.33561196, 3546.65976544,  488.72396282, 3673.62999582,
        533.8041452 ,  639.57196489, 5526.00778799, 3722.26541596,
       4251.47990303, 4902.77264821, 4965.53141253, 4811.09993749,
       4943.86242742, 1211.44056591, 2994.51492197, 3633.17580508,
       3180.78519914, 2392.3755801 , 1804.66550566, 1761.94102094,
       2964.36660988, 3727.45807872, 3142.58371347, 3033.8549028 ,
       1095.64460832, 4358.29662479, 2430.61975465, 2418.16842728,
        731.54700546, 4415.84780936, 1256.9731461 , 4316.12567794,
        635.97771212, 4262.19262163, 4368.2820738 , 5567.29555725,
        517.24552294, 3089.56851639, 3097.76800505,  636.16465565,
        553.32765567,  570.06617901, 4273.56428847, 4961.57566466,
       5439.61461365, 4911.60000642, 4995.49875339, 5491.90238168,
       3127.87286195,  543.90918076, 3702.33144621, 3040.22964945,
       4234.39184178, 1888.28336583, 2992.18488269, 1737.68955878,
       1100.26986044, 5004.29132275, 4949.2517071 , 1172.75426251,
       2552.4255307 , 4862.3713461 , 4911.35889095, 3730.01311365,
       3762.6421022 , 3097.45476266, 5523.63204733, 4369.08251367,
       1796.73657051,  518.57038159,  499.49987576, 3620.16606398,
       4934.76602152, 2455.19720899, 1854.15441378, 4962.85515168,
       3676.65324454, 5606.47693653, 1694.05322474, 3009.88005774,
       1843.16005803, 1284.11949817,  609.33647619, 1904.7515219 ,
       2419.40399581, 1132.00194259, 3587.29639648, 1372.53853468,
       3109.09276638, 5594.75904811,  654.42257865, 4465.78018271,
       4336.2201929 ,  534.36165993, 1168.28371556, 1870.40319045,
       4988.62157333,  610.4252396 , 5481.90322933, 1219.75026119,
       4251.67893645, 3696.98649479, 1924.05033972, 1219.01592195,
       2995.04617063, 3622.53969114,  563.64606074, 4340.95633764,
        697.47148454, 4944.48941307, 1301.12055311, 4833.38113564,
       2441.05489196, 2427.60393183, 4391.3974573 ,  554.65117793,
       3672.27138087, 5116.10106702, 2376.06108582,  623.25807744,
       4904.0346155 , 4201.97367225, 4336.81101657,  550.89268058,
        556.24760796, 3710.98723991, 3554.87822696,  534.4408038 ,
       4919.98375588, 1723.97442768, 4861.30270488, 4854.54812388,
       2388.5225486 , 5554.40210103, 2297.99044655,  523.64937787,
       4286.92253494, 4920.95846978,  590.7479238 , 3548.86780166,
       1813.65485142, 3778.72499493, 4904.7237262 , 1886.11118858,
        660.31267786, 3089.79726491, 5448.3632913 , 2474.04715851,
        579.55917184, 1901.54220272, 1784.7860104 , 5548.87796255,
       3607.91256719, 4326.42615352, 2974.3819188 , 4285.70472561,
       4953.6349439 , 1771.29011519, 5633.16078086, 1212.71898279,
        555.90286629, 5455.52953442, 1145.45394608, 4959.29568775,
       4261.82501071, 2547.99873195,  521.91691298,  537.74405031,
       5446.96363766, 5664.76395106, 5490.72863436,  686.12255469,
       3701.21786991, 1200.51866765, 4868.48704779, 4248.20936947,
       3630.14819665, 5002.56110407, 1170.04828655, 4355.26333579,
       1964.71142632, 4330.75099222, 4853.36242065,  592.44069765,
        597.33738716, 3657.03776078, 5535.05045892, 4357.35162599,
       2471.23187578, 2955.19195996, 1926.98131132, 1096.98364358,
       4278.6004364 , 4246.56619469, 1962.25865529, 5692.84639484,
       4366.40279296, 5648.9386234 , 2355.28977341, 1774.90898383,
        545.73437014, 1287.07800301,  523.55965122, 5491.90419134,
       5584.18562846, 2479.96936383, 1823.05885669, 1186.05471814,
       3796.4551183 ,  450.69615517, 4462.76825757, 5581.48115918,
       1180.51747319, 5481.00524281, 2436.22213716, 3171.78927296,
       4200.78753249, 1299.99052722, 2319.06801198, 5732.78778213,
       5544.25438741, 4300.25270568, 3833.20572272, 3154.13574342,
       3071.12332009, 4382.4306139 , 4292.49563889, 4348.96848336,
       3685.98545266, 5497.63462967, 4935.9042137 , 2396.62023155,
       1284.32199145, 1223.11637227, 1985.02704009, 3224.31193339,
       5006.21388848, 5547.06967013, 1234.95282936, 3098.09052142,
       5536.80663983, 5652.77462525, 4924.87002209, 2497.18090803,
       4305.08135092, 2470.87219163, 2026.19177376,  592.52667142,
       4928.75035219, 1253.98972241, 1215.63983493, 4420.22923649,
       4942.35706085, 2508.07744007, 1764.42740476, 1821.96889045,
       3666.61094085, 5558.80099435, 1266.6245702 , 2976.43705953,
        617.50221938, 5456.18157247, 4916.411925  , 3700.95910201,
       1775.68886498, 5492.76584559, 4852.78174321, 5632.61038904,
       3110.95915391, 3028.21893428, 3126.25669277, 4916.13253405,
       1148.88916076, 4780.63136606, 3626.14858383, 2488.30815143,
       3758.86402517, 1310.91916536, 1178.36901197, 1228.76127337,
       2305.02457798, 2488.16080381, 3127.65650587, 1297.59080429,
        532.2221848 , 1149.00058103, 4397.01055656, 4281.88682355,
       5515.65817709,  679.38348669, 3113.17125683, 1849.4488309 ,
       2561.11298314, 1112.54931945, 1297.51314032, 2400.57490929,
       4366.54211867, 4769.32481128, 2962.67518368, 3009.53786655,
       3699.62067358, 1970.14671123, 5532.85179181, 3783.50253443,
       2464.58734193, 4363.69936705,  620.37812047, 1901.71078023,
       4248.10409307,  569.39832496, 3195.63943223, 1371.79317613,
       4806.3364298 , 4985.98558486, 4209.15559866, 2424.0123618 ,
        705.87736416, 1731.80899898,  617.44187807, 4438.49315857,
       3140.578027  , 3085.70655231, 2460.65845613, 1241.20602032,
        481.74063329,  605.16302588, 3625.44409368, 5080.26275928,
       1239.19701751, 5520.0249643 , 5485.2512674 , 3028.90697485,
       4321.57513946, 2458.0714599 , 1225.66736599, 4810.00714371,
        639.25153525, 1858.30829523, 4280.28797703,  601.1877251 ,
       4358.48000169, 2512.10872246, 4294.40964424, 3075.83860184,
       5521.45433303, 4828.26611008, 2457.49242183, 4198.27699612,
        496.86388729, 2569.72787213, 5604.6380179 , 5424.31872499,
       5574.99123938, 1941.2143988 , 3583.21807633, 1346.28429277,
       5488.32320408, 4454.12546315, 3074.169161  , 1120.96759151,
       1943.07034664, 3007.45105625, 3057.00967479, 3688.97021273])

In [ ]:
print("mean absulute error", mean_squared_error(y_test, y_pred))
print("r2_score", r2_score(y_test,y_pred))
print("mse" ,mean_squared_error(y_test, y_pred))

mean absulute error 3857652.746269827
r2_score 0.385128041926163
mse 3857652.746269827

In [ ]:
import pickle

# Save the trained model to a file
with open('sales_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [ ]:
pickle.dump(le_product, open("product_encoder.pkl", "wb"))
pickle.dump(le_category, open("category_encoder.pkl", "wb"))
pickle.dump(le_region, open("region_encoder.pkl", "wb"))